# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.03.10
_src_path: gh:scientific-python/cookie
backend: hatch
email: nikib@uw.edu
full_name: University of Washington - SSEC
license: BSD
org: uw-ssec
project_name: genetic-forensic-portal
project_short_description: A web frontend for the submission and analysis of anti-poaching
    genetic forensic data.
url: https://github.com/uw-ssec/genetic-forensic-portal
vcs: true
